services:
  - type: web
    name: rick-portfolio
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: APP_KEY
        value: base64:4YQ3rLJRzYGbRbZ6pN8Q6fX7M9K2L1wN5vP3J8F2D6A=
